--- 
  - name: openjdk11 instatll
    hosts: all 
    become: yes
    tasks: 
      - name: openjdk11 
        ansible.builtin.apt: 
          name: openjdk-11-jdk 
          state: present
          update_cache: yes 
    
